# Generated by Django 6.0.5 on 2026-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=100, verbose_name='Contesting For'),
        ),
    ]
