# Generated by Django 6.0.5 on 2026-06-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_candidate_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='party',
            new_name='contesting_for',
        ),
    ]
